service:  sevenone
image: shocker21323/sevenone
servers:
  - 64.227.25.47
  - 24.199.80.250
registry:
  username: shocker21323
  password:
    - MRSK_REGISTRY_PASSWORD
env:
  clear:
    DB_HOST:
  secret:
    - RAILS_MASTER_KEY
accessories:
  db:
    image: mysql:8.0
    host: 192.241.141.71
    port: 3306
    env:
      clear:
        MYSQL_ROOT_HOST: '%'
      secret:
        - MYSQL_ROOT_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql
# Configure custom arguments for Traefik
# traefik:
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000
